'use client';

import React from 'react';
import { motion } from 'framer-motion';
import { useAudit } from '../../context/AuditContext';
import { SECTORS, DEPARTMENTS, SECTOR_DEPARTMENTS, IOT_SENSORS, STANDARDS } from '../../data';
import { StatCard } from '../common/StatCard';
import { DepartmentScoreChart } from '../common/DepartmentScoreChart';
import { AnimatedPage, StaggerGrid } from '../common/AnimatedPage';
import { ScrollReveal } from '../common/ScrollReveal';
import { getSectorLatestScores, calculateSectorMetrics } from '../../utils/calculations';
import { staggerChild, staggerChildScale, cardHover, cardTap } from '../../utils/animations';
import { formatLiveClocks } from '../../utils/date';

export const DashboardView: React.FC = () => {
  const {
    isAr,
    currentSector,
    setCurrentSector,
    setActiveTab,
    startAudit,
    archivedAudits,
    ncrs,
    suppliers,
    capas,
    trainings,
    calibrations,
    iotTelemetry,
    isTelemetrySimulating,
    toggleTelemetrySimulation,
    dispatchWhatsApp,
    printReport,
  } = useAudit();

  const sectorDeptKeys = SECTOR_DEPARTMENTS[currentSector] || [];
  const sectorScores = getSectorLatestScores(archivedAudits, sectorDeptKeys);
  const metrics = calculateSectorMetrics(sectorScores, sectorDeptKeys, ncrs);

  const currentSectorObj = SECTORS.find(s => s.val === currentSector);
  const sensors = IOT_SENSORS[currentSector] || IOT_SENSORS.hotels || [];

  // Standards breakdown for current sector
  const sectorStandards = STANDARDS.filter(s => s.sectors.includes(currentSector));
  const isoStandardsCount = sectorStandards.filter(s => s.standard.toLowerCase().includes('iso')).length;
  const oshaStandardsCount = sectorStandards.filter(s => s.standard.toLowerCase().includes('osha')).length;
  const haccpStandardsCount = sectorStandards.filter(s => s.standard.toLowerCase().includes('haccp') || s.standard.toLowerCase().includes('food')).length;
  const otherStandardsCount = sectorStandards.length - (isoStandardsCount + oshaStandardsCount + haccpStandardsCount);

  // Chart data
  const chartData = sectorDeptKeys.slice(0, 12).map(key => {
    const deptInfo = DEPARTMENTS[key];
    const name = deptInfo ? (isAr ? deptInfo.ar : deptInfo.en) : key;
    return {
      deptKey: key,
      name: name.length > 22 ? name.substring(0, 22) + '...' : name,
      score: key in sectorScores ? sectorScores[key] : null,
    };
  });

  const handleShareExecutiveSummary = () => {
    const nowClocks = formatLiveClocks(new Date(), isAr);
    const sectorName = currentSectorObj ? (isAr ? currentSectorObj.ar : currentSectorObj.en) : currentSector;
    const msg = isAr
      ? `*تقرير الملخص التنفيذي للجودة والتدقيق*\nالقطاع: ${sectorName}\nالتاريخ: ${nowClocks.gregorianDate} - ${nowClocks.time}\n------------------------\n• نسبة الامتثال العامة: ${metrics.averageScore}%\n• تغطية الأقسام: ${metrics.coveragePercent}%\n• عدد الأقسام المدققة: ${metrics.auditedCount} من ${metrics.totalDepts}\n• الوفورات المحققة: $${metrics.estimatedSavings.toLocaleString()}\n• الغرامات المتجنبة: $${metrics.penaltiesAvoided.toLocaleString()}\n• مذكرات NCR المفتوحة: ${metrics.openNcrs}\n------------------------\nتم الإصدار عبر منصة التدقيق الرقمية المعتمدة.`
      : `*Executive Quality & Compliance Summary*\nSector: ${sectorName}\nDate: ${nowClocks.gregorianDate} - ${nowClocks.time}\n------------------------\n• Overall Compliance: ${metrics.averageScore}%\n• Dept Coverage: ${metrics.coveragePercent}%\n• Audited: ${metrics.auditedCount} of ${metrics.totalDepts} depts\n• Cost Savings: $${metrics.estimatedSavings.toLocaleString()}\n• Penalties Avoided: $${metrics.penaltiesAvoided.toLocaleString()}\n• Open NCRs: ${metrics.openNcrs}\n------------------------\nGenerated by Certified Digital Audit Panel.`;

    dispatchWhatsApp(msg);
  };

  return (
    <AnimatedPage>
      {/* Sector Selector Tabs Bar */}
      <div className="bg-white dark:bg-slate-900 rounded-3xl p-4 sm:p-5 border border-slate-200 dark:border-slate-800 shadow-sm transition-colors">
        <div className="flex items-center justify-between gap-3 mb-3 px-1">
          <div className="flex items-center gap-2 text-xs font-bold text-slate-600 dark:text-slate-300">
            <span className="text-sky-500 text-sm">🏭</span>
            <span>{isAr ? 'اختر قطاع التشغيل والتدقيق:' : 'Select Industry Sector:'}</span>
          </div>
          <div className="flex items-center gap-2">
            <motion.button
              whileHover={{ scale: 1.03 }}
              whileTap={{ scale: 0.96 }}
              type="button"
              onClick={handleShareExecutiveSummary}
              className="flex items-center gap-1.5 px-3.5 py-1.5 rounded-xl bg-[#25D366] hover:bg-[#1EBE5D] text-white text-xs font-bold shadow-sm transition-colors"
            >
              <span className="text-xs">📲</span>
              <span className="hidden sm:inline">{isAr ? 'مشاركة الملخص' : 'Share Summary'}</span>
            </motion.button>
            <motion.button
              whileHover={{ scale: 1.03 }}
              whileTap={{ scale: 0.96 }}
              type="button"
              onClick={printReport}
              className="flex items-center gap-1.5 px-3.5 py-1.5 rounded-xl bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-200 text-xs font-bold border border-slate-300 dark:border-slate-700 transition-colors"
            >
              <span className="text-xs">🖨️</span>
              <span className="hidden sm:inline">{isAr ? 'طباعة تقرير A4' : 'Print A4 PDF'}</span>
            </motion.button>
          </div>
        </div>

        <div className="flex items-center gap-1.5 overflow-x-auto pb-1.5 scrollbar-none">
          {SECTORS.map(sec => {
            const isSelected = currentSector === sec.val;
            return (
              <motion.button
                whileTap={{ scale: 0.95 }}
                key={sec.val}
                type="button"
                onClick={() => setCurrentSector(sec.val)}
                className={`px-4 py-2.5 rounded-2xl text-xs font-bold whitespace-nowrap transition-all flex items-center gap-2 shrink-0 ${
                  isSelected
                    ? 'bg-sky-600 text-white shadow-lg shadow-sky-600/30 scale-[1.02]'
                    : 'bg-slate-100 dark:bg-slate-800/80 text-slate-600 dark:text-slate-400 hover:bg-slate-200 dark:hover:bg-slate-800 hover:text-slate-900 dark:hover:text-white'
                }`}
              >
                <span>{isAr ? sec.ar : sec.en}</span>
              </motion.button>
            );
          })}
        </div>
      </div>

      {/* KPI Cards Grid */}
      <StaggerGrid className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        <StatCard
          title={isAr ? 'نسبة الامتثال العامة' : 'Overall Compliance Score'}
          value={`${metrics.averageScore}%`}
          subtitle={
            isAr
              ? `🎯 ${metrics.auditedCount} من ${metrics.totalDepts} قسماً مدققاً`
              : `🎯 ${metrics.auditedCount} of ${metrics.totalDepts} depts audited`
          }
          icon={<span className="text-xl select-none">📊</span>}
          variant={metrics.averageScore >= 85 ? 'emerald' : metrics.averageScore >= 70 ? 'amber' : 'rose'}
          trend={metrics.averageScore >= 80 ? '+4.2%' : undefined}
        />

        <StatCard
          title={isAr ? 'تغطية الأقسام المدققة' : 'Department Audit Coverage'}
          value={`${metrics.coveragePercent}%`}
          subtitle={
            isAr
              ? `⏳ ${metrics.totalDepts - metrics.auditedCount} أقسام متبقية`
              : `⏳ ${metrics.totalDepts - metrics.auditedCount} pending audits`
          }
          icon={<span className="text-xl select-none">📋</span>}
          variant="sky"
        />

        <StatCard
          title={isAr ? 'الوفورات المحققة تقديرياً' : 'Estimated Cost Savings'}
          value={`$${metrics.estimatedSavings.toLocaleString()}`}
          subtitle={isAr ? '💡 عبر معالجة الهدر والحيود' : '💡 Via waste & deviation fixes'}
          icon={<span className="text-xl select-none">💰</span>}
          variant="emerald"
        />

        <StatCard
          title={isAr ? 'الغرامات والمخالفات المتجنبة' : 'Fines & Penalties Avoided'}
          value={`$${metrics.penaltiesAvoided.toLocaleString()}`}
          subtitle={
            isAr
              ? `✅ إغلاق ${metrics.closedNcrs} مذكرة حيود (NCR)`
              : `✅ ${metrics.closedNcrs} resolved NCR tickets`
          }
          icon={<span className="text-xl select-none">🛡️</span>}
          variant="indigo"
        />
      </StaggerGrid>

      {/* Mission Modules Control Grid */}
      <StaggerGrid className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3.5">
        {/* 1. Suppliers AVL */}
        <motion.div
          variants={staggerChild}
          whileHover={cardHover}
          whileTap={cardTap}
          onClick={() => setActiveTab('suppliers')}
          className="p-4 rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-sm hover:border-indigo-500 hover:shadow-md cursor-pointer transition-all group flex items-center justify-between"
        >
          <div className="space-y-0.5">
            <span className="text-[11px] font-bold text-slate-500 dark:text-slate-400 block uppercase">
              {isAr ? 'الموردين المعتمدين (AVL)' : 'Approved Vendors'}
            </span>
            <div className="flex items-baseline gap-1.5">
              <span className="text-xl font-black font-mono text-indigo-600 dark:text-indigo-400">
                {suppliers.filter(s => s.status === 'APPROVED').length}
              </span>
              <span className="text-[10px] text-slate-400 font-medium">
                {isAr ? `من أصل ${suppliers.length}` : `of ${suppliers.length}`}
              </span>
            </div>
          </div>
          <div className="w-10 h-10 rounded-xl bg-indigo-500/10 text-indigo-600 dark:text-indigo-400 flex items-center justify-center group-hover:scale-110 transition-transform">
            <span className="text-lg">🚚</span>
          </div>
        </motion.div>

        {/* 2. CAPA Master Tracker */}
        <motion.div
          variants={staggerChild}
          whileHover={cardHover}
          whileTap={cardTap}
          onClick={() => setActiveTab('capa')}
          className="p-4 rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-sm hover:border-rose-500 hover:shadow-md cursor-pointer transition-all group flex items-center justify-between"
        >
          <div className="space-y-0.5">
            <span className="text-[11px] font-bold text-slate-500 dark:text-slate-400 block uppercase">
              {isAr ? 'مسار تصحيح CAPA' : 'Active CAPAs'}
            </span>
            <div className="flex items-baseline gap-1.5">
              <span className="text-xl font-black font-mono text-rose-600 dark:text-rose-400">
                {capas.filter(c => c.status !== 'CLOSED').length}
              </span>
              <span className="text-[10px] text-slate-400 font-medium">
                {isAr ? `من إجمالي ${capas.length}` : `of ${capas.length}`}
              </span>
            </div>
          </div>
          <div className="w-10 h-10 rounded-xl bg-rose-500/10 text-rose-600 dark:text-rose-400 flex items-center justify-center group-hover:scale-110 transition-transform">
            <span className="text-lg">🔄</span>
          </div>
        </motion.div>

        {/* 3. Training Matrix */}
        <motion.div
          variants={staggerChild}
          whileHover={cardHover}
          whileTap={cardTap}
          onClick={() => setActiveTab('training')}
          className="p-4 rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-sm hover:border-emerald-500 hover:shadow-md cursor-pointer transition-all group flex items-center justify-between"
        >
          <div className="space-y-0.5">
            <span className="text-[11px] font-bold text-slate-500 dark:text-slate-400 block uppercase">
              {isAr ? 'كفاءة وتدريب الطاقم' : 'Certified Staff'}
            </span>
            <div className="flex items-baseline gap-1.5">
              <span className="text-xl font-black font-mono text-emerald-600 dark:text-emerald-400">
                {trainings.filter(t => t.status === 'VALID').length}
              </span>
              <span className="text-[10px] text-slate-400 font-medium">
                {isAr ? `من ${trainings.length} موظف` : `of ${trainings.length}`}
              </span>
            </div>
          </div>
          <div className="w-10 h-10 rounded-xl bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 flex items-center justify-center group-hover:scale-110 transition-transform">
            <span className="text-lg">🎓</span>
          </div>
        </motion.div>

        {/* 4. Calibration Log */}
        <motion.div
          variants={staggerChild}
          whileHover={cardHover}
          whileTap={cardTap}
          onClick={() => setActiveTab('calibration')}
          className="p-4 rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-sm hover:border-sky-500 hover:shadow-md cursor-pointer transition-all group flex items-center justify-between"
        >
          <div className="space-y-0.5">
            <span className="text-[11px] font-bold text-slate-500 dark:text-slate-400 block uppercase">
              {isAr ? 'معايرة الأجهزة والمجسات' : 'Calibrated Sensors'}
            </span>
            <div className="flex items-baseline gap-1.5">
              <span className="text-xl font-black font-mono text-sky-600 dark:text-sky-400">
                {calibrations.filter(c => c.status === 'VALID').length}
              </span>
              <span className="text-[10px] text-slate-400 font-medium">
                {isAr ? `من ${calibrations.length} جهاز` : `of ${calibrations.length}`}
              </span>
            </div>
          </div>
          <div className="w-10 h-10 rounded-xl bg-sky-500/10 text-sky-600 dark:text-sky-400 flex items-center justify-center group-hover:scale-110 transition-transform">
            <span className="text-lg">⚖️</span>
          </div>
        </motion.div>
      </StaggerGrid>

      {/* Standards Framework Widget & Live Telemetry Grid */}
      <ScrollReveal>
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
          {/* Live IoT Telemetry Monitoring Bar (8 cols) */}
          <div className="lg:col-span-8 bg-white dark:bg-slate-900 rounded-3xl p-5 sm:p-6 border border-slate-200 dark:border-slate-800 shadow-sm space-y-3">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <span className="relative flex h-3 w-3">
                  <span
                    className={`animate-ping absolute inline-flex h-full w-full rounded-full opacity-75 ${
                      isTelemetrySimulating ? 'bg-emerald-400' : 'bg-slate-400'
                    }`}
                  />
                  <span
                    className={`relative inline-flex rounded-full h-3 w-3 ${
                      isTelemetrySimulating ? 'bg-emerald-500' : 'bg-slate-500'
                    }`}
                  />
                </span>
                <h4 className="text-xs font-black uppercase tracking-wider text-slate-800 dark:text-slate-200">
                  {isAr ? '📡 حساسات المراقبة المباشرة (Live IoT Telemetry)' : '📡 Live IoT Telemetry Sensors'}
                </h4>
              </div>

              <div className="flex items-center gap-3">
                <button
                  type="button"
                  onClick={() => setActiveTab('iot')}
                  className="text-[11px] font-bold text-sky-600 dark:text-sky-400 hover:underline flex items-center gap-1 transition-all hover:scale-105"
                >
                  <span>{isAr ? '📡 محطة المراقبة الكاملة' : '📡 Full Stream Station'}</span>
                  <i className="fa-solid fa-arrow-left text-[9px] rtl:inline ltr:hidden"></i>
                  <i className="fa-solid fa-arrow-right text-[9px] ltr:inline rtl:hidden"></i>
                </button>

                <motion.button
                  whileTap={{ scale: 0.92 }}
                  type="button"
                  onClick={toggleTelemetrySimulation}
                  className="text-[11px] font-bold text-slate-500 hover:text-sky-500 flex items-center gap-1.5 px-2.5 py-1 rounded-lg bg-slate-100 dark:bg-slate-800 transition-colors"
                >
                  <span>{isTelemetrySimulating ? '⏸️' : '▶️'}</span>
                  <span>
                    {isAr
                      ? isTelemetrySimulating
                        ? 'إيقاف'
                        : 'تشغيل'
                      : isTelemetrySimulating
                      ? 'Pause'
                      : 'Play'}
                  </span>
                </motion.button>
              </div>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-3">
              {sensors.map(sensor => {
                const val = iotTelemetry[sensor.id];
                const isWarning = val === 'WARNING';
                return (
                  <motion.div
                    key={sensor.id}
                    whileHover={{ scale: 1.02 }}
                    className={`p-3.5 rounded-2xl border transition-all ${
                      isWarning
                        ? 'bg-rose-500/10 border-rose-500/50 text-rose-600 dark:text-rose-400 animate-pulse'
                        : 'bg-slate-50 dark:bg-slate-950/60 border-slate-200 dark:border-slate-800/80 text-slate-800 dark:text-slate-200 hover:border-sky-500/40'
                    }`}
                  >
                    <div className="flex items-center justify-between text-[11px] mb-1">
                      <span className="font-bold truncate text-slate-500 dark:text-slate-400">
                        {isAr ? sensor.labelAr : sensor.labelEn}
                      </span>
                      <i className={`fa-solid ${sensor.icon} text-sky-500`}></i>
                    </div>
                    <div className="text-base sm:text-lg font-black font-mono flex items-baseline gap-1">
                      <span>{val ?? sensor.init}</span>
                      <span className="text-[10px] text-slate-400 font-sans font-bold">{sensor.unit}</span>
                    </div>
                  </motion.div>
                );
              })}
            </div>
          </div>

          {/* Standards Framework Summary Card (4 cols) */}
          <div className="lg:col-span-4 bg-white dark:bg-slate-900 rounded-3xl p-5 sm:p-6 border border-slate-200 dark:border-slate-800 shadow-sm space-y-3 flex flex-col justify-between">
            <div>
              <h4 className="text-xs font-black uppercase tracking-wider text-slate-800 dark:text-slate-200 mb-1 flex items-center gap-2">
                <span className="text-amber-500">📜</span>
                <span>{isAr ? 'أطر ومعايير الاعتماد للقطاع' : 'Certified Standards Framework'}</span>
              </h4>
              <p className="text-[11px] text-slate-500 mb-3">
                {isAr
                  ? `🎯 ${sectorStandards.length} معياراً تشغيلياً نشطاً لهذا القطاع`
                  : `🎯 ${sectorStandards.length} active standards mapped to sector`}
              </p>

              <div className="grid grid-cols-2 gap-2 text-center text-xs">
                <div className="p-3 rounded-2xl bg-indigo-500/10 border border-indigo-500/20 space-y-0.5 transition-transform hover:scale-105">
                  <span className="text-[10px] font-bold text-indigo-600 dark:text-indigo-400 uppercase block">🏛️ ISO Standards</span>
                  <span className="text-lg font-black font-mono text-indigo-700 dark:text-indigo-300">{isoStandardsCount}</span>
                </div>
                <div className="p-3 rounded-2xl bg-sky-500/10 border border-sky-500/20 space-y-0.5 transition-transform hover:scale-105">
                  <span className="text-[10px] font-bold text-sky-600 dark:text-sky-400 uppercase block">⛑️ OSHA Safety</span>
                  <span className="text-lg font-black font-mono text-sky-700 dark:text-sky-300">{oshaStandardsCount}</span>
                </div>
                <div className="p-3 rounded-2xl bg-emerald-500/10 border border-emerald-500/20 space-y-0.5 transition-transform hover:scale-105">
                  <span className="text-[10px] font-bold text-emerald-600 dark:text-emerald-400 uppercase block">🛡️ HACCP / Food</span>
                  <span className="text-lg font-black font-mono text-emerald-700 dark:text-emerald-300">{haccpStandardsCount}</span>
                </div>
                <div className="p-3 rounded-2xl bg-purple-500/10 border border-purple-500/20 space-y-0.5 transition-transform hover:scale-105">
                  <span className="text-[10px] font-bold text-purple-600 dark:text-purple-400 uppercase block">💊 SFDA / GMP</span>
                  <span className="text-lg font-black font-mono text-purple-700 dark:text-purple-300">{Math.max(1, otherStandardsCount)}</span>
                </div>
              </div>
            </div>

            <div className="pt-2 text-center">
              <span className="text-[10px] font-bold text-emerald-600 dark:text-emerald-400 flex items-center justify-center gap-1">
                <span>✅</span>
                <span>{isAr ? 'معايير ممتثلة للمواصفات الدولية 2026' : '100% Compliant with 2026 Specifications'}</span>
              </span>
            </div>
          </div>
        </div>
      </ScrollReveal>

      {/* Main Grid: Department Score Distribution & Quick Audit Cards */}
      <ScrollReveal>
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
          {/* Left Column: Department Score Breakdown Chart (7 cols) */}
          <div className="lg:col-span-7 bg-white dark:bg-slate-900 rounded-3xl p-5 sm:p-6 border border-slate-200 dark:border-slate-800 shadow-sm space-y-4">
            <div className="flex items-center justify-between pb-3 border-b border-slate-200 dark:border-slate-800">
              <div>
                <h4 className="text-sm font-black text-slate-900 dark:text-white">
                  {isAr ? '📊 توزيع درجات الامتثال حسب الأقسام' : '📊 Department Compliance Distribution'}
                </h4>
                <p className="text-[11px] text-slate-500">
                  {isAr
                    ? 'مؤشرات الأداء الفعلية بناءً على آخر جولات التدقيق المعتمدة'
                    : 'Actual performance based on latest certified audits'}
                </p>
              </div>
              <span className="text-[10px] font-bold px-2.5 py-1 rounded-lg bg-sky-500/10 text-sky-600 dark:text-sky-400 border border-sky-500/20">
                {isAr ? `✅ ${metrics.auditedCount} تم تدقيقها` : `✅ ${metrics.auditedCount} Audited`}
              </span>
            </div>

            <DepartmentScoreChart data={chartData} onSelectDept={deptKey => startAudit(deptKey)} />
          </div>

          {/* Right Column: Quick Audit Action Grid (5 cols) */}
          <div className="lg:col-span-5 bg-white dark:bg-slate-900 rounded-3xl p-5 sm:p-6 border border-slate-200 dark:border-slate-800 shadow-sm space-y-4">
            <div className="flex items-center justify-between pb-3 border-b border-slate-200 dark:border-slate-800">
              <div>
                <h4 className="text-sm font-black text-slate-900 dark:text-white">
                  {isAr ? '⚡ بدء جولة تدقيق فورية' : '⚡ Start Instant Audit Session'}
                </h4>
                <p className="text-[11px] text-slate-500">
                  {isAr ? 'اختر القسم لتحميل المعايير وبدء الفحص' : 'Select a department to load standards'}
                </p>
              </div>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-2.5 max-h-[420px] overflow-y-auto pe-1">
              {sectorDeptKeys.map(key => {
                const deptInfo = DEPARTMENTS[key];
                const name = deptInfo ? (isAr ? deptInfo.ar : deptInfo.en) : key;
                const hasScore = key in sectorScores;
                const score = sectorScores[key];
                const standardsCount = STANDARDS.filter(
                  s => s.sectors.includes(currentSector) && s.depts.includes(key)
                ).length;

                return (
                  <motion.button
                    whileHover={{ scale: 1.025, y: -2 }}
                    whileTap={{ scale: 0.97 }}
                    key={key}
                    type="button"
                    onClick={() => startAudit(key)}
                    className={`p-3.5 rounded-2xl border text-start transition-all flex flex-col justify-between group ${
                      hasScore
                        ? 'bg-emerald-500/5 hover:bg-emerald-500/10 border-emerald-500/30'
                        : 'bg-slate-50 dark:bg-slate-950/60 hover:bg-slate-100 dark:hover:bg-slate-800 border-slate-200 dark:border-slate-800'
                    }`}
                  >
                    <div className="space-y-1">
                      <span className="text-xs font-black text-slate-900 dark:text-white block group-hover:text-sky-500 transition-colors">
                        {name}
                      </span>
                      <span className="text-[10px] text-slate-500 dark:text-slate-400 font-bold block">
                        {isAr ? `📋 ${standardsCount} معياراً تشغيلياً` : `📋 ${standardsCount} Standards`}
                      </span>
                    </div>

                    <div className="flex items-center justify-between pt-3 mt-2 border-t border-slate-200/60 dark:border-slate-800/60 w-full">
                      <span className="text-[10px] font-bold text-sky-600 dark:text-sky-400 flex items-center gap-1">
                        <span>{isAr ? '⚡ بدء الفحص' : '⚡ Start Audit'}</span>
                        <i className="fa-solid fa-arrow-left text-[9px] rtl:inline ltr:hidden"></i>
                        <i className="fa-solid fa-arrow-right text-[9px] ltr:inline rtl:hidden"></i>
                      </span>
                      {hasScore && (
                        <span className="text-[11px] font-mono font-black text-emerald-600 dark:text-emerald-400">
                          {score}%
                        </span>
                      )}
                    </div>
                  </motion.button>
                );
              })}
            </div>
          </div>
        </div>
      </ScrollReveal>
    </AnimatedPage>
  );
};
