import { TabKey } from '../types';

export const PATH_TO_TAB: Record<string, TabKey> = {
  '/': 'dashboard',
  '/dashboard': 'dashboard',
  '/audit': 'audit_form',
  '/audit-form': 'audit_form',
  '/kpi': 'kpi',
  '/standards': 'kpi',
  '/ncr': 'ncr',
  '/capa': 'capa',
  '/suppliers': 'suppliers',
  '/training': 'training',
  '/calibration': 'calibration',
  '/iot': 'iot',
  '/haccp': 'haccp',
  '/recall': 'recall',
  '/ai': 'ai',
  '/visitors': 'visitors',
  '/sustainability': 'sustainability',
  '/emergency': 'emergency',
  '/archive': 'archive',
  '/settings': 'settings',
};

export const TAB_TO_PATH: Record<TabKey, string> = {
  dashboard: '/',
  audit_form: '/audit',
  kpi: '/kpi',
  ncr: '/ncr',
  capa: '/capa',
  suppliers: '/suppliers',
  training: '/training',
  calibration: '/calibration',
  iot: '/iot',
  haccp: '/haccp',
  recall: '/recall',
  ai: '/ai',
  visitors: '/visitors',
  sustainability: '/sustainability',
  emergency: '/emergency',
  archive: '/archive',
  settings: '/settings',
};
